apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=781017761620.dkr.ecr.us-east-1.amazonaws.com/mern-repo
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds           
    argocd-image-updater.argoproj.io/git-branch: main                                          
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/ycetin94/image-updater.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd


  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
